Insert into user_account (user_id, date_created, username, password, email)
Values (1, date '2015-04-09' + time '13:45:03', 'Rosalind', 'rosalindPass', 'rosa@gmail.com');
Insert into user_account (user_id, date_created, username, password, email)
Values (2, date '2015-04-09' + time '13:45:03', 'Horatio', 'horatioPass', 'horatio@gmail.com');
Insert into user_account (user_id, date_created, username, password, email)
Values (3, date '2015-04-09' + time '13:45:03', 'Von', 'vonPass', 'von@gmail.com');
Insert into user_account (user_id, date_created, username, password, email)
Values (4, date '2015-04-09' + time '13:45:03', 'Moe', 'moePass', 'moe@gmail.com');
Insert into user_account (user_id, date_created, username, password, email)
Values (5, date '2015-04-09' + time '13:45:03', 'Kevin', 'kevPass', 'kev@gmail.com');